name: Keepalive Workflow
on:
  schedule:
    # 每月1号的UTC时间0点运行，即北京时间上午8点左右
    - cron: '0 0 1 * *'
  workflow_dispatch: # 支持手动运行

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
